library(drake)
library(rmarkdown)
library(bookdown)
library(tinytex)
library(kableExtra)
library(knitr)
library(plyr)
library(dplyr)
library(tidyr)
library(tibble)
library(lubridate)
library(scales)
library(tidyselect)
library(HDInterval)
library(emmeans)
library(gamm4)
library(MuMIn)
library(mgcv)
library(brms)
library(rstan)
library(parallel)
library(ggplot2)
library(bayesplot)
library(ggsci)
library(CHNOSZ)
# for LoLinR
# use function "install_github"
# from the remotes package
# with repo = "colin-olito/LoLinR"
library(LoLinR)
library(gridExtra)
library(Hmisc)
library(ggpubr)
library(grid)
library(png)
library(ggnewscale)
library(cowplot)
library(vegan)
library(tidybayes)
library(ggdist)
